// Generated Data Model

export struct AppData {
    current-temp: float,
    target-temp: float,
    time-remaining: float,
    cook-progress: float,
    cooking-status: string,
    basket-status: string,
    cooking-presets: string,
    temp-unit: string,
    auto-preheat: bool,
    shake-reminder: bool,
    screen-brightness: float,
    sound-enabled: bool,
    last-cleaned: string,
    total-usage-hours: float,
}
